version: '3.8'

services:
  mysql:
    container_name: MySQL-EIP2
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: eip
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql-mode=""
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
